<?php 
    $this->headTitle()->prepend('Productos');
    echo $this->headTitle();
?>
<h1>Productos<a style="float: right; text-decoration: none"href="/catalogos/producto/nuevo">Nuevo</a></h1>
<?php if(count($successMessages)) :?>
    <div class="units-row">
        <?php foreach ($successMessages as $message) :?>
            <div class="unit-100">    
                <div class="tools-alert tools-alert-green">
                    <?php echo $message?>
                </div> 
            </div>
        <?php endforeach;?>
    </div>
<?php endif;?>
<table>
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>Costo</th>
            <th>Precio</th>
            <th>Opciones</th>   
        </tr>
    </thead>
    <tbody>
        <?php foreach($collection as $entity) : ?>
            <tr id="<?php echo $entity['idproducto']?>">
                 <td><?php echo $entity['producto_nombre']?></td>
                <td><?php echo $entity['producto_descripcion']?></td>
                <td><?php echo $entity['producto_costo']?></td>
                <td><?php echo $entity['producto_precio']?></td>
                <td class="tr_options"><a href="<?php echo '/catalogos/producto/editar/'.$entity['idproducto']?>">Editar</a><a class="delete-modal" href="javascript:void(0)" data-tools="modal" data-width="700" data-title="<h2>Advertencia</h2>" data-content="/catalogos/producto/eliminar?html=true&idproducto=<?php echo $entity['idproducto']?>" >Eliminar</a></td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>
<script>
$(function()
{
    
    $.ajax({
        url: '/json/lang_es_datatable.json',
        dataType: 'json',
        success: function(data){
            var table = $('table').DataTable({
                language:data,
            });
            table.on( 'draw', function () {
                $('[data-tools="modal"]').modal();
            });
        }
    });
    
    $('.delete-modal').on('loading.tools.modal', function(modal)
    {   
        
        var $modalHeader = this.$modalHeader;
        $modalHeader.addClass('modal_header_warning');
        var id = this.$element.closest('tr').attr('id');
        var $modal = this ;
        
        this.createCancelButton('Cancelar');
        
        
        if(modal.find('.can_delete').length == 0){
            
        }else{
            
            var buttonDelete = this.createDeleteButton('Eliminar');

            buttonDelete.on('click', $.proxy(function()
            {
                //Hacemos la peticion ajax
                $.ajax({
                    url:'/catalogos/producto/eliminar/'+id,
                    dataType: 'json',
                    method:'POST',
                    success: function(data){
                        if(data.response){
                            $modal.close();
                            window.location.replace('/catalogos/producto');
                        }
                    }
                });


            }, this));
        }
        

        

    });
    
    //Damos formato a nuestra taba
    $('table tr').each(function(){
       var str =  $(this).find('td').eq(2).text();
       $(this).find('td').eq(2).text(accounting.formatMoney(str));
       var str =  $(this).find('td').eq(3).text();
       $(this).find('td').eq(3).text(accounting.formatMoney(str));
      
    });
    
});
</script>