<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('FeetCenter '. $this->translate('Administrador'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath('css/style.css'))
                         ->prependStylesheet($this->basePath('css/plugin/multiple.css'))
                        ->prependStylesheet($this->basePath('css/plugin/datatable/jquery.dataTables.css'))
                        ->prependStylesheet($this->basePath('css/plugin/default.date.css'))
                        ->prependStylesheet($this->basePath('css/plugin/default.css'))
                        ->prependStylesheet($this->basePath('css/kube.css')) ?>

                        
        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath('/js/plugin/multiple.js'))
            ->prependFile($this->basePath('js/plugin/datatable/jquery.dataTables.js'))
            ->prependFile($this->basePath('js/plugin/picker.date.js'))
            ->prependFile($this->basePath('js/plugin/picker.js'))
            ->prependFile($this->basePath('js/plugin/lolliclock.js'))
            ->prependFile($this->basePath('js/plugin/accounting.js')) 
            ->prependFile($this->basePath('js/plugin/numeric.js'))     
            ->prependFile($this->basePath('js/form.js'))
            ->prependFile($this->basePath('js/kube.min.js'))
            ->prependFile($this->basePath('js/jquery.min.js'));
        ?>

    </head>
    <body>
        <header id="top_header" class="group z-depth-1">
            <nav id="top_header_resources" class="navbar navbar-left">
                <ul>
                    <li><img width="60" height="60" src="/img/logo/top_logo.png"></li>
                    <li><a href="#">Agenda</a></li>
                    <li><a href="#" data-tools="dropdown" data-target="#dropdown-pacientes">Pacientes</a></li>
                    <li><a href="#" data-tools="dropdown" data-target="#dropdown-ventas">Ventas</a></li>
                    <li><a href="#"  data-tools="dropdown" data-target="#dropdown-inventarios">Inventarios</a></li>
                    <li><a href="#">Comisiones</a></li>
                    <li><a href="#" data-tools="dropdown" data-target="#dropdown-egresos">Egresos</a></li>
                    <li><a href="#" data-tools="dropdown" data-target="#dropdown-compras">Compras</a></li>
                    <li><a href="#" data-tools="dropdown" data-target="#dropdown-catalogos">Catalogos</a></li>
                    <li><a href="#">Configuracion</a></li>
                    <li><a href="#" data-tools="dropdown" data-target="#dropdown-reportes">Reportes</a></li>
                </ul>
            </nav>
            <nav class="navbar navbar-right">
                <ul>
                    <li style="float: right" id="profile_container" ><img width="35" height="35" src="<?php echo Shared\Session\AouthSession::getEmpleadoFoto()?>" class="circle"><a href="#" data-tools="dropdown" data-target="#dropdown-profile" style="display: inline; margin-left: 12px; margin-right: 12px;"><?php echo Shared\Session\AouthSession::getEmpleadoNombre()?></a></li>
                </ul>
            </nav>
        </header>
        <!--Dropdown-->
        <ul id="dropdown-profile" class="dropdown">
            <li><a href="/login/out">Cerrar sesión</a></li>
        </ul>
        <ul id="dropdown-pacientes" class="dropdown">
            <li><a href="#">Nuevo paciente</a></li>
            <li><a href="#">Pacientes</a></li>
            <li><a href="#">Expediente</a></li>
            <li><a href="#">Seguimiento</a></li>
        </ul>
        <ul id="dropdown-ventas" class="dropdown">
            <li><a href="#">Ventas</a></li>
            <li><a href="#">Nueva venta</a></li>
            <li><a href="#">Balance</a></li>
        </ul>
        <ul id="dropdown-inventarios" class="dropdown">
            <li><a href="#">Transferencias</a></li>
            <li><a href="#">Nueva transferencia</a></li>
            <li><a href="/inventario/existencias">Definir existencias</a></li>
            <li><a href="#">Definir precio y reorden</a></li>
            <li><a href="/inventario/producto">Productos</a></li>
            <li><a href="/inventario/insumo">Insumos</a></li>
        </ul>
        <ul id="dropdown-egresos" class="dropdown">
            <li><a href="#">Egresos</a></li>
            <li><a href="#">Nuevo egreso</a></li>
        </ul>
        <ul id="dropdown-compras" class="dropdown">
            <li><a href="/compras">Compras</a></li>
            <li><a href="/compras/nuevo">Nueva compra</a></li>
        </ul>
        <ul id="dropdown-catalogos" class="dropdown">
            <li><a href="/catalogos/clinica">Clinicas</a></li>
            <li><a href="/catalogos/empleado">Empleados</a></li>
            <li><a href="/catalogos/servicio">Servicios</a></li>
            <li><a href="/catalogos/producto">Productos</a></li>
            <li><a href="/catalogos/insumo">Insumos</a></li>
            <li><a href="/catalogos/rol">Roles</a></li>
            <li><a href="/catalogos/proveedor">Proveedores</a></li>
            <li><a href="/catalogos/canal">Canal de comunicación</a></li>
        </ul>
        <ul id="dropdown-reportes" class="dropdown">
            <li><a href="#">Clinicas</a></li>
            <li><a href="#">Empleados</a></li>
        </ul>
            <div class="units-row">
                <div class="unit-centered unit-90">
                    <?php echo $this->content; ?>
                </div>
            </div>
            
 
            <footer>
                
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
