<?php 
    $this->headTitle()->prepend('Seguimiento cliente');
    echo $this->headTitle();
?>
<div id="clinica_container">
    <h1>Seguimiento #<?php echo $id ?>(<?php echo $paciente->getPacienteNombre()?>)</h1>
    <?php 
        $form->setAttribute('action', '/pacientes/seguimiento/'.$paciente->getIdpaciente().'/editar/'.$id);
        $form->setAttribute('novalidate', true);
        $form->setAttribute('class', 'forms');
        $form->prepare();
        echo $this->form()->openTag($form); 
    ?>
    <div class="units-row">
        
        <div class="unit-50">
            <label style="margin-bottom: 0px">
                Fecha <span class="req">*</span>
                <?php echo $this->formHidden($form->get('idpaciente')); ?>
            </label>
            <?php echo $this->formText($form->get('pacienteseguimiento_fecha')); ?>
        </div>
        <div class="unit-50">
            <label style="margin-bottom: 0px">
                Hora (Formato 24 hrs) <span class="req">*</span>
            </label>
            <?php echo $this->formText($form->get('pacienteseguimiento_hora')); ?>
        </div>
    </div>
    <div class="units-row">
        <div class="unit-50">
            <label>
                Canal de comunicación <span class="req">*</span>
                <?php echo $this->formSelect($form->get('idcanalcomunicacion')); ?>
            </label>
        </div>
        <div class="unit-50">
            <label>
                Estatus de seguimiento <span class="req">*</span>
                <?php echo $this->formSelect($form->get('idestatusseguimiento')); ?>
            </label>
        </div>
    </div>
    <div class="units-row">
        <div class="unit-100">
            <label>
                Comentario <span class="req">*</span>
                <?php echo $this->formTextarea($form->get('pacienteseguimiento_comentario')); ?>
            </label>
        </div>
    </div>
    <div class="units-row">
        <div class="unit-centered unit-40"><button data-action="submit" class="btn btn-green">Guardar</button></div>
    </div>
</div>
<script>
    
    $('input[name=pacienteseguimiento_fecha]').pickadate({
                monthsFull: [ 'enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre' ],
                monthsShort: [ 'ene', 'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'nov', 'dic' ],
                weekdaysFull: [ 'domingo', 'lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado' ],
                weekdaysShort: [ 'dom', 'lun', 'mar', 'mié', 'jue', 'vie', 'sáb' ],
                today: 'hoy',
                clear: 'borrar',
                close: 'cerrar',
                firstDay: 1,
                format: 'd !de mmmm !de yyyy',
                formatSubmit: 'yyyy/mm/dd',
                //selectYears: true,
                selectMonths: true,
                selectYears: 25,
            });
            
    $('input[name=pacienteseguimiento_hora]').timepicker({
                minuteStep: 1,
                template: 'modal',
                appendWidgetTo: 'div.modal section',
                showSeconds: false,
                showMeridian: false,
                defaultTime: false
        });
</script>
