<?php 
    $this->headTitle()->prepend('Faltantes');
    echo $this->headTitle();
?>
<h1>Faltantes<a style="float: right; text-decoration: none"href="/empleados/faltantes/nuevo">Nuevo</a></h1>
<?php if(count($successMessages)) :?>
    <div class="units-row">
        <?php foreach ($successMessages as $message) :?>
            <div class="unit-100">    
                <div class="tools-alert tools-alert-green">
                    <?php echo $message?>
                </div> 
            </div>
        <?php endforeach;?>
    </div>
<?php endif;?>
<table>
    <thead>
        <tr>
            <th>Fecha</th>
            <th>Hora</th>
            <th>Clínica</th>
            <th>Generó</th>
            <th>Recibió</th>
            <th>Cantidad</th>
            <th>Generar comprobante</th>
            <th>Comprobante firmado</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <?php $entity = new Faltante()?>
    <tbody>
        <?php foreach($collection as $entity) : ?>
        
            <tr id="<?php echo $entity->getIdfaltante()?>">
                <td><?php echo $entity->getFaltanteFecha('d/m/Y')?></td>
                <td><?php echo $entity->getFaltanteHora()?></td>
                <td><?php echo $entity->getClinica()->getClinicaNombre()?></td>
                <td><?php echo $entity->getEmpleadoRelatedByIdempleadogenerador()->getEmpleadoNombre()?></td>
                <td><?php echo $entity->getEmpleadoRelatedByIdempleadodeudor()->getEmpleadoNombre()?></td>
                <td><?php echo $entity->getFaltanteCantidad()?></td>
                <td><button class="btn btn-blue generarCombrobante">Generar</button></td>
                <?php if(!is_null($entity->getFaltanteComprobantefirmado())) :?>
                    <td><a href="<?php echo $entity->getFaltanteComprobantefirmado() ?>"><img src="/img/icons/pdf_icon.png"></a></td>
                <?php else :?>
                    <td>N/D</td>
                <?php endif;?>
                <td class="tr_options"><a href="<?php echo '/empleados/faltantes/editar/'.$entity->getIdfaltante()?>">Editar</a><a class="delete-modal" href="javascript:void(0)" data-tools="modal" data-width="700" data-title="<h2>Advertencia</h2>" data-content="/empleados/faltantes/eliminar?html=true" >Eliminar</a></td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>
<script src="/js/download.js"></script>
<script>
$(function()
{   
    $('table .generarCombrobante').on('click',function(){
        
        var id = $(this).closest('tr').attr('id');
        
        $.ajax({
            url:'/empleados/faltantes/generarcomprobante',
            dataType:'json',
            data:{id:id},
            success:function(data){
                download('data:application/pdf;base64,'+data, "comprobante.pdf", "application/pdf");
            }
        });
                
        
    });
    
    $.ajax({
        url: '/json/lang_es_datatable.json',
        dataType: 'json',
        success: function(data){
            var table = $('table').DataTable({
                language:data,
            });
            table.on( 'draw', function () {
                $('[data-tools="modal"]').modal();
            });
        }
    });
    
    $('.delete-modal').on('loading.tools.modal', function(modal)
    {
        var $modalHeader = this.$modalHeader;
        $modalHeader.addClass('modal_header_warning');
        var id = this.$element.closest('tr').attr('id');
        var $modal = this ;
        
        this.createCancelButton('Cancelar');

        var buttonDelete = this.createDeleteButton('Eliminar');

        buttonDelete.on('click', $.proxy(function()
        {
            //Hacemos la peticion ajax
            $.ajax({
                url:'/empleados/faltantes/eliminar/'+id,
                dataType: 'json',
                method:'POST',
                success: function(data){
                    if(data.response){
                        $modal.close();
                        window.location.replace('/empleados/faltantes');
                    }else{
                        window.location.replace('/empleados/faltantes/404');
                    }
                }
            });

            
        }, this));

    });
});
</script>