<?php 
    $this->headTitle()->prepend('Metas de clínicas');
    echo $this->headTitle();
?>
<h1>Meta clínicas<a style="float: right; text-decoration: none"href="/catalogos/metaclinica/nuevo">Nuevo</a></h1>
<?php if(count($successMessages)) :?>
    <div class="units-row">
        <?php foreach ($successMessages as $message) :?>
            <div class="unit-100">    
                <div class="tools-alert tools-alert-green">
                    <?php echo $message?>
                </div> 
            </div>
        <?php endforeach;?>
    </div>
<?php endif;?>
<table>
    <thead>
        <tr>
            <th>Clínica</th>
            <th>Meta</th>
            <th>Logrado</th>
            <th>Año</th>
            <th>Mes</th>
            <th>Opciones</th>
            
        </tr>
    </thead>
    <tbody>
        <?php 
            $months = array(
                1 => 'Enero',
                2 => 'Febrero',
                3 => 'Marzo',
                4 => 'Abril',
                5 => 'Mayo',
                6 => 'Junio',
                7 => 'Julio',
                8 => 'Agosto',
                9 => 'Septiembre',
                10 => 'Octubre',
                11 => 'Noviembre',
                12 => 'Diciembre',
            );
        
        ?>
        <?php foreach($collection as $entity) : ?>
            <tr id="<?php echo $entity['idmetaclinica']?>">
                <?php $clinica= \ClinicaQuery::create()->filterByIdclinica($entity['idclinica'])->findOne(); ?>
                <td><?php echo $clinica->getClinicaNombre(); ?></td>
                <td><?php echo $entity['metaclinica_meta']?></td>
                <td><?php echo $entity['metaclinica_meta']?></td>
                <td><?php echo $entity['metaclinica_anio']?></td>
                <td><?php echo $months[$entity['metaclinica_mes']]?></td>
                <td class="tr_options"><a href="<?php echo '/catalogos/metaclinica/editar/'.$entity['idmetaclinica']?>">Editar</a><a class="delete-modal" href="javascript:void(0)" data-tools="modal" data-width="700" data-title="<h2>Advertencia</h2>" data-content="/catalogos/clinica/eliminar?html=true" >Eliminar</a></td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>
<script>
$(function()
{
    
    $.ajax({
        url: '/json/lang_es_datatable.json',
        dataType: 'json',
        success: function(data){
            var table = $('table').DataTable({
                
                language:data,
            });
            
            
            
            
            table.on( 'draw', function () {
                $('[data-tools="modal"]').modal();
            });
        }
    });
    
    
    $('.delete-modal').on('loading.tools.modal', function(modal)
    {
        var $modalHeader = this.$modalHeader;
        $modalHeader.addClass('modal_header_warning');
        var id = this.$element.closest('tr').attr('id');
        var $modal = this ;
        
        this.createCancelButton('Cancelar');

        var buttonDelete = this.createDeleteButton('Eliminar');

        buttonDelete.on('click', $.proxy(function()
        {
            //Hacemos la peticion ajax
            $.ajax({
                url:'/catalogos/metaclinica/eliminar/'+id,
                dataType: 'json',
                method:'POST',
                success: function(data){
                    if(data.response){
                        $modal.close();
                        window.location.replace('/catalogos/metaclinica');
                    }
                }
            });

            
        }, this));

    });
});
</script>