<?php 
    $this->headTitle()->prepend('Comisiones');
    echo $this->headTitle();
?>
<div id="empleados_comisiones_container">
    
    <h1>Comisiones</h1>
    <div class="units-row">
        <div class="unit-30">
            Clínica
            <select multiple="multiple" name="idclinica" class="width-100">
                <?php foreach ($clinicas as $clinica) : ?>
                    <option value="<?php echo $clinica->getIdclinica()?>"><?php echo $clinica->getClinicaNombre() ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="unit-70" id="filter_container">
            <label style="display: block">Filtrar por periodo de tiempo</label>
            <input placeholder="Desde" type="email" name="comisiones_from" class="width-6" />
            <input placeholder="Hasta" type="email" name="comisiones_to" class="width-6" />
            <button id="filterbydate" class="btn btn-blue" style="height: 30px;"><i class="fa fa-filter"></i> </button>
        </div>
    </div>
    <table class="table-comisiones table-bordered">
        <thead>
        </thead>
        <tbody>
        </tbody>
        <tfoot>
            
        </tfoot>
    </table>
</div>
<script src="/plugins/fullcalendar/moment.js"></script>
<script src="/js/empleados/comisiones.js"></script>
<script>
    var comisiones = $('#empleados_comisiones_container').comisiones({
        idclinica: <?php echo $idclinica?>,
    });
    comisiones.init();
    
</script>