<link href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" media="all" rel="stylesheet" type="text/css" />
<link href="/css/plugin/monthpicker.css" media="all" rel="stylesheet" type="text/css" />

<?php 
    $this->headTitle()->prepend('Productos y servicios vendidos');
    echo $this->headTitle();
?>
<div id="empleados_vendidos_container">
    <h1>Productos y servicios vendidos</h1>
    <div class="units-row">
        <div class="unit-30">
            Clínica
            <select multiple="multiple" name="idclinica" class="width-100">
                <?php foreach ($clinicas as $clinica) : ?>
                    <option value="<?php echo $clinica->getIdclinica()?>"><?php echo $clinica->getClinicaNombre() ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="unit-30">
           Servicios
            <select multiple="multiple" name="idservicio" class="width-100">
                <?php foreach ($servicios as $servicio) : ?>
                    <option value="<?php echo $servicio->getIdservicio()?>"><?php echo $servicio->getServicionombre() ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="unit-30">
           Membresías
            <select multiple="multiple" name="idmembresia" class="width-100">
                <?php foreach ($membresias as $membresia) : ?>
                    <option value="<?php echo $membresia->getIdmembresia()?>"><?php echo $membresia->getMembresianombre() ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="unit-30">
           Productos
            <select multiple="multiple" name="idproducto" class="width-100">
                <?php foreach ($productos as $producto) : ?>
                    <option value="<?php echo $producto->getIdproducto()?>"><?php echo $producto->getProductonombre() ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="unit-20" id="month_filter_container">
            <label style="display: block">Fecha inicial</label>
            <input placeholder="Fecha inicial" type="text" name="month_filter" class="width-100" />
        </div>
        <div class="unit-20" id="month_filter_container">
            <label style="display: block">Fecha final</label>
            <input placeholder="Fecha final" type="text" name="month_filter2" class="width-60" />
            <button id="filterbydate" class="btn btn-blue" style="height: 30px;"><i class="fa fa-filter"></i> </button>
        </div>
    </div>
    <div class="units-row">
        <div class="unit-50">
            <table class="table-vendidos-servicios table-bordered">
            <thead>
            </thead>
            <tbody>
            </tbody>
            <tfoot>
            </tfoot>
            </table>
        </div>
        <div class="unit-50">
            <table class="table-vendidos-productos table-bordered">
            <thead>
            </thead>
            <tbody>
            </tbody>
            <tfoot>
            </tfoot>
            </table>
        </div>
    </div>
    

</div>
<script src="http://code.jquery.com/ui/1.10.2/jquery-ui.js" type="text/javascript"></script>
<script src="/plugins/monthPicker/monthPicker.js"></script>
<script src="/plugins/fullcalendar/moment.js"></script>
<script src="/js/empleados/vendidos.js"></script>
<script>
    var vendidos = $('#empleados_vendidos_container').vendidos({
        session: <?php echo $session?>,
    });
    
    vendidos.init();
    
</script>