
<div id="membresia_container">
     <h1>Membresia: <?php echo $form->get('membresia_nombre')->getValue()?></h1>
    <?php 
        $form->setAttribute('action', '/catalogos/membresias/editar/'.$id);
        $form->setAttribute('novalidate', true);
        $form->setAttribute('class', 'forms');
        $form->prepare();
        echo $this->form()->openTag($form); 
    ?>
    <div class="units-row">
        <div class="unit-100">
            <label>
                Nombre <span class="req">*</span>
                <?php echo $this->formText($form->get('membresia_nombre')); ?>
            </label>
        </div>
    </div>
    <div class="units-row">
        <div class="unit-100">
            <label>
                Descripción <span class="req">*</span>
                <?php echo $this->formTextarea($form->get('membresia_descripcion')); ?>
            </label>
        </div>
    </div>
    <div class="units-row">
        <div class="unit-33">
            <label>
                Cantidad de servicios <span class="req">*</span>
                <?php echo $this->formText($form->get('membresia_servicios')); ?>
            </label>
        </div>
        <div class="unit-33">
            <label>
                Cantidad de cupones <span class="req">*</span>
                <?php echo $this->formText($form->get('membresia_cupones')); ?>
            </label>
        </div>
        <div class="unit-33">
            <label>
                Precio <span class="req">*</span>
                <?php echo $this->formText($form->get('membresia_precio')); ?>
            </label>
        </div>
    </div>
    <div class="units-row">
        <div class="unit-100">
            <fieldset>
                <legend>Ingresos y comisiones</legend>
                <div class="units-row">
                    <div class="unit-33">
                        <label>
                            <b>
                              Genera ingreso <span class="req">*</span>  
                            </b> 
                        </label>
                        <ul class="forms-inline-list">
                            <?php echo $this->formRadio($form->get('servicio_generaingreso')); ?>
                        </ul>
                    </div>
                    <div class="unit-33">
                        <label>
                            <b>
                                 Genera comisión <span class="req">*</span>
                            </b> 
                        </label>
                        <ul class="forms-inline-list">
                            <?php echo $this->formRadio($form->get('servicio_generacomision')); ?>
                        </ul>
                    </div>
                    <div class="unit-33">
                        <div class="units-row">
                            <div class="unit-50">
                                <label><b>Tipo de comisión</b></label>
                                <?php echo $this->formSelect($form->get('servicio_tipocomision')); ?>
                            </div>
                            <div class="unit-50">
                                <label><b>Cantidad de comisión</b></label>
                                <?php echo $this->formText($form->get('servicio_comision')); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
    <div class="units-row">
        <div class="unit-centered unit-40"><button data-action="submit" class="btn btn-green">Guardar</button></div>
    </div>
</div>
<script src="/js/catalogos/membresia.js"></script>
<script>
    $('#membresia_container').membresia();
</script>