<?php 
    $this->headTitle()->prepend('Membresías');
    echo $this->headTitle();
?>
<h1>Membresías<a style="float: right; text-decoration: none"href="/catalogos/membresias/nuevo">Nuevo</a></h1>
<?php if(count($successMessages)) :?>
    <div class="units-row">
        <?php foreach ($successMessages as $message) :?>
            <div class="unit-100">    
                <div class="tools-alert tools-alert-green">
                    <?php echo $message?>
                </div> 
            </div>
        <?php endforeach;?>
    </div>
<?php endif;?>
<table>
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>No. servicios</th>
            <th>No. cupones</th>   
            <th>Precio</th>   
            <th>Opciones</th>   
        </tr>
    </thead>
    <tbody>
        <?php $entity = new Membresia()?>
        <?php foreach($collection as $entity) : ?>
            <tr id="<?php echo $entity->getIdmembresia()?>">
                <td><?php echo $entity->getMembresiaNombre()?></td>
                <td><?php echo $entity->getMembresiaDescripcion()?></td>
                <td><?php echo (int)$entity->getMembresiaServicios()?></td>
                <td><?php echo (int)$entity->getMembresiaCupones()?></td>
                <td><?php echo $entity->getMembresiaPrecio()?></td>
                <td class="tr_options"><a href="<?php echo '/catalogos/membresias/editar/'.$entity->getIdmembresia()?>">Editar</a></td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>
<script>
$(function()
{
    $.ajax({
        url: '/json/lang_es_datatable.json',
        dataType: 'json',
        success: function(data){
            var table = $('table').DataTable({
                language:data,
            });
            table.on( 'draw', function () {
                $('[data-tools="modal"]').modal();
            });
        }
    });
    
    $('.delete-modal').on('loading.tools.modal', function(modal)
    {
        var $modalHeader = this.$modalHeader;
        $modalHeader.addClass('modal_header_warning');
        var id = this.$element.closest('tr').attr('id');
        var $modal = this ;
        
        this.createCancelButton('Cancelar');

        var buttonDelete = this.createDeleteButton('Eliminar');

        buttonDelete.on('click', $.proxy(function()
        {
            //Hacemos la peticion ajax
            $.ajax({
                url:'/catalogos/membresias/eliminar/'+id,
                dataType: 'json',
                method:'POST',
                success: function(data){
                    if(data.response){
                        $modal.close();
                        window.location.replace('/catalogos/membresias');
                    }
                }
            });

            
        }, this));

    });
    
    //Damos formato a nuestra taba
    $('table tr').each(function(){
       var str =  $(this).find('td').eq(4).text();
       $(this).find('td').eq(4).text(accounting.formatMoney(str));      
    });
    
    
});
</script>