<?php 
    $this->headTitle()->prepend('Nueva membresía');
    echo $this->headTitle();
?>
<div id="membresia_container">
    <h1>Nueva Membresía</h1>
    <?php 
        $form->setAttribute('action', '/catalogos/membresias/nuevo');
        $form->setAttribute('novalidate', true);
        $form->setAttribute('class', 'forms');
        $form->prepare();
        echo $this->form()->openTag($form); 
    ?>
    <div class="units-row">
        <div class="unit-100">
            <label>
                Nombre <span class="req">*</span>
                <?php echo $this->formText($form->get('membresia_nombre')); ?>
            </label>
        </div>
    </div>
    <div class="units-row">
        <div class="unit-100">
            <label>
                Descripción <span class="req">*</span>
                <?php echo $this->formTextarea($form->get('membresia_descripcion')); ?>
            </label>
        </div>
    </div>
    <div class="units-row">
        <div class="unit-33">
            <label>
                Cantidad de servicios <span class="req">*</span>
                <?php echo $this->formText($form->get('membresia_servicios')); ?>
            </label>
        </div>
        <div class="unit-33">
            <label>
                Cantidad de cupones <span class="req">*</span>
                <?php echo $this->formText($form->get('membresia_cupones')); ?>
            </label>
        </div>
        <div class="unit-33">
            <label>
                Precio <span class="req">*</span>
                <?php echo $this->formText($form->get('membresia_precio')); ?>
            </label>
        </div>
    </div>

    <div class="units-row">
        <div class="unit-centered unit-40"><button data-action="submit" class="btn btn-green">Guardar</button></div>
    </div>
</div>
<script src="/js/catalogos/membresia.js"></script>
<script>
    $('#membresia_container').membresia();
</script>