<div id="grupo_container">
     <h1>Grupo: <?php echo $form->get('grupo_nombre')->getValue()?></h1>
    <?php 
        $form->setAttribute('action', '/pacientes/grupos/editar/'.$id);
        $form->setAttribute('novalidate', true);
        $form->setAttribute('class', 'forms');
        $form->prepare();
        echo $this->form()->openTag($form); 
    ?>
    <div class="units-row">
        <div class="unit-50">
            <label>
                Nombre <span class="req">*</span>
                <?php echo $this->formText($form->get('grupo_nombre')); ?>
            </label>
        </div>
    </div>
    <div class="units-row">
        <div class="unit-100">
            <label>
                Descripción
                <?php echo $this->formTextarea($form->get('grupo_descripcion')); ?>
            </label>
        </div>
    </div>
    <div class="units-row">
        <div class="unit-100">
            <fieldset>
                <legend>Clientes</legend>
                <div class="units-row">
                    <div class="unit-80">
                      Nombre
                      <input class="width-100"type="text" name="paciente_autocomplete">  
                    </div>
                    <div class="unit-20" style="margin-top: 4px;">
                        <a data-action="addPaciente" class="btn btn-blue" style="height: 30px; margin-top: 20px; width: 100%;">Agregar</a>
                    </div>
                </div>
                <table id="tabla_pacientes">
                    <thead>
                        <tr>
                            <th>Clínica</th>
                            <th>Nombre</th>
                            <th>Celular</th>
                            <th>Teléfono</th>
                            <th>Opciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php $paciente = new Grupopaciente();?>
                        <?php foreach ($pacientes as $paciente) :?>
                        <tr id="<?php echo $paciente->getPaciente()->getIdpaciente()?>">
                            <input type="hidden" value="<?php echo $paciente->getPaciente()->getIdpaciente()?>" name="pacientes[]">
                            <td><?php echo $paciente->getPaciente()->getClinica()->getClinicaNombre()?></td>
                            <td><?php echo $paciente->getPaciente()->getPacienteNombre()?></td>
                            <td><?php echo $paciente->getPaciente()->getPacienteCelular()?></td>
                            <td><?php echo $paciente->getPaciente()->getPacienteTelefono()?></td>
                            <td>
                            <a href="javascript:void(0)">Eliminar</a>
                            </td>
                        </tr>
                        <?php endforeach;?>
                    </tbody>
                </table>
            </fieldset>
        </div>
    </div>

    <div class="units-row">
        <div class="unit-centered unit-40"><button data-action="submit" class="btn btn-green">Guardar</button></div>
    </div>
</div>
<script src="/js/pacientes/grupos.js"></script>
<script>
    var grupoFrom = $('#grupo_container').grupos();
    grupoFrom.form();
</script>