<div id="agenda_container">
    <h1>Agenda</h1>
    <?php if(count($successMessages)) :?>
        <div class="units-row">
            <?php foreach ($successMessages as $message) :?>
                <div class="unit-100">    
                    <div class="tools-alert tools-alert-green">
                        <?php echo $message?>
                    </div> 
                </div>
            <?php endforeach;?>
        </div>
    <?php endif;?>
    <div class="units-row">
        <div class="unit-30">
            Clinica
            <select multiple="multiple" name="idclinica" class="width-100">
                <?php foreach ($clinicas as $clinica) : ?>
                    <option value="<?php echo $clinica->getIdclinica()?>"><?php echo $clinica->getClinicaNombre() ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <div id='calendar'></div>
</div>
<script src='bower_components/fullcalendar/moment/min/moment.min.js'></script>
<script src='bower_components/fullcalendar/fullcalendar/dist/fullcalendar.js'></script>
<script src='bower_components/fullcalendar/fullcalendar-scheduler/dist/scheduler.js'></script>
<script src='bower_components/fullcalendar/fullcalendar/dist/lang/es.js'></script>
<script src='/js/agenda/agenda.js'></script>
<script>
    var agenda = $('#agenda_container').agenda({
        idclinica: <?php echo $idclinica?>,
    });
    agenda.init();
</script>