<style>
    .disable {

      background-color: rgb(255, 190, 190);

    }
    
    .fc-widget-header{
        background-color: #FFF;
    }
    
    .agenda_descanso{
        cursor: not-allowed;
        width: 100%;
    }
    
    .por_confirmar{
        background: #fb8c00;
    }
    
    .receso{
        background: #00bcd4;
    }
</style>
<div id="agenda_container">
    <h1>Agenda</h1>
    <?php if(count($successMessages)) :?>
        <div class="units-row">yellow;
            <?php foreach ($successMessages as $message) :?>
                <div class="unit-100">    
                    <div class="tools-alert tools-alert-green">
                        <?php echo $message?>
                    </div> 
                </div>
            <?php endforeach;?>
        </div>
    <?php endif;?>
    <div class="units-row">
        <div class="unit-30">
            Clinica
            <select multiple="multiple" name="idclinica" class="width-100">
                <?php foreach ($clinicas as $clinica) : ?>
                    <option value="<?php echo $clinica->getIdclinica()?>"><?php echo $clinica->getClinicaNombre() ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="unit-30">
            <label>
                Fecha   
                <input class="width-100" type="text" name="agenda_fecha" style="height: 26px;">
            </label>
        </div>
    </div>
    <div id='calendar'></div>
</div>
<script src="/plugins/fullcalendar/moment.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.1/moment.min.js"></script>
<script src="/plugins/fullcalendar/fullcalendar.js"></script>
<script src="/plugins/fullcalendar/lang/es.js"></script>
<script src='/js/agenda/agenda.js'></script>
<script>
    var agenda = $('#agenda_container').agenda({
        idclinica: <?php echo $idclinica?>,
    });
    agenda.init();
</script>