<style>
    .nuevo_paciente_close{
        position: absolute;
        right: 8px;
        top: -8px;
        color: #bbb;
        cursor: pointer;
        font-size: 15px;
        font-weight: 300;
    }
    
    .nuevo_paciente_close:hover{
        color: #000;
    }
    
    .relacionados_close{
        position: absolute;
        right: 8px;
        top: -8px;
        color: #bbb;
        cursor: pointer;
        font-size: 15px;
        font-weight: 300;
    }
    
    .relacionados_close:hover{
        color: #000;
    }
</style>
<div id="modal_event_container">
    <?php echo $this->formHidden($form->get('idclinica')); ?>
    <?php echo $this->formHidden($form->get('idempleado')); ?>
    
    <div class="units-row" style="margin-bottom: 10px;">
        <?php 
            echo $this->form()->openTag($form); 
        ?>
        <div class="unit-50">
            <div><span><b>Pedicurista: </b></span><span><?php echo $empleado->getEmpleadoNombre() ?></span></div>
        </div>
        <div class="unit-50">
            <div><span><b>Fecha y hora: </b></span><span><?php echo $fecha->format('d/m/Y').' - '.$fecha->format('H:i') ?></span></div>
        </div>
    </div>
    <div class="units-row" style="margin-bottom: 0px;">
        <div class="unit-60">
            <label>
            <b>Paciente </b><span class="req">*</span>
            <?php echo $this->formText($form->get('idpaciente')); ?>
            </label>
            <div class="units-row" style="margin-bottom: 12px;">
                <div class="unit-33">
                    <div><span><b>Total de visitas: </b></span><span id="visita_total"></span></div>
                </div>
                <div class="unit-60">
                     <div><span><b>Ultima visita: </b></span><span id="visita_ultima"></span></div>
                </div>
            </div>
        </div>
        <div class="unit-40" style="margin-top: 25px;">
              <button btn-action="open_paciente_container" class="btn" style="height: 30px;">Nuevo</button>
              <button btn-action="open_relacionados_container" class="btn btn-disabled" style="margin-left: 7px; height: 30px;" disabled>Relacionados</button>
        </div>
    </div>
    <div id="paciente_container" class="units-row" style="display: none">
        <div class="unit-100">
            <fieldset style="position: relative">
                <span class="nuevo_paciente_close">x</span>
                <legend>Nuevo paciente</legend>
                <div class="units-row" style="margin-bottom: 0px;">                  
                    <div class="unit-100">
                        <label>
                            Nombre <span class="req">*</span>
                            <input required name="paciente_nombre" type="text" class="width-100">
                        </label>
                    </div>
                </div>
                <div class="units-row">
                    <div class="unit-50">
                        <label>
                            Celular <span class="req">*</span>
                            <input required name="paciente_celular" type="text" class="width-100">
                        </label>
                    </div>
                    <div class="unit-50">
                        <label>
                            Confirmar celular <span class="req">*</span>
                            <input required name="paciente_celular_confirmar" type="text" class="width-100">
                        </label>
                    </div>
                </div>
                <div class="units-row">
                    <div class="unit-40 centered">
                        <button btn-action="submit_paciente" class="btn btn-green width-100">Guardar</button>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
    <div id="relacionados_container" class="units-row" style="display: block">
        <div class="unit-100">
            <fieldset style="position: relative">
                <span class=relacionados_close">x</span>
                <legend>Pacientes relacionados</legend>
                <div class="units-row" style="margin-bottom: 0px;">
                    <div class="unit-100">
                        
                    </div>
                </div>     
            </fieldset>
        </div>
    </div>
</div>
<script src="/js/agenda/modalEvent.js"></script>
<script>
    $('#modal_event_container').modalEvent();
</script>