<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

<?php 
    $this->headTitle()->prepend('Horarios Vacíos');
    echo $this->headTitle();
?>
<div id="horarios_container">
    <h1>Horarios </h1>
    <div class="units-row">
        <div class="unit-30">
            Clinica
            <select multiple="multiple" name="idclinica" class="width-100">
                <?php $clinica = new clinica()?>;
                <?php foreach ($clinicas as $key => $value) : ?>
                <option idclinica="<?php echo$key ?>" value="<?php echo $key?>"><?php echo $value ?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="unit-70" id="filter_container">
            <label style="display: block">Periodo de tiempo</label>
            <input placeholder="Desde" type="email" name="filter_from" class="width-6" />
            <input type="hidden" name="filter_from_hidden" class="width-6" />
            <input placeholder="Hasta" type="text" name="filter_to" class="width-6" />
            <input type="hidden" name="filter_to_hidden" class="width-6" />
            <button id="filterbydate" class="btn btn-blue" style="height: 30px;"><i class="fa fa-filter"></i> </button>
        </div>
    </div>
    <div class="units-row">
        <div class="unit-100">
            <table class="table-bordered" id="table_clinica">
            <thead>
             <th>10:00</th>
            <th>10:30</th>
            <th>11:00</th>
            <th>11:30</th>
            <th>12:00</th>
            <th>12:30</th>
            <th>13:00</th>
            <th>13:30</th>
            <th>14:00</th>
            <th>14:30</th>
            <th>15:00</th>
            <th>15:30</th>
            <th>16:00</th>
            <th>16:30</th>
            <th>17:00</th>
            <th>17:30</th>
            <th>18:00</th>
            <th>18:30</th>
            <th>19:00</th>
            <th>19:30</th>
            <th>20:00</th>
            <th>20:30</th>
            </thead>
            <tbody>

            </tbody>
            <tfoot>
            </tfoot>
            </table>
        </div>
    </div>
</div>
<script src="/plugins/accounting.js"></script>
<script src="/plugins/fullcalendar/moment.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="/js/datepicker-es.js"></script>
<script src="/js/reportes/horariosvacios.js"></script>
<script>
    $('#horarios_container').horariosvacios();
</script>