<p>
    <b>Estatus:</b>
    <select class="width-100" name="transferencia_estatus">
        <?php foreach ($status as $key => $value) :?>
            <option value="<?php echo $key?>"><?php echo $value?></option>
        <?php endforeach;?>
    </select>
</p>
<p id="transferencia_nota_container" style="display: none">
    <b>Nota: <span class="req">*</span></b> 
    <textarea name="transferencia_nota"></textarea>
</p>
<script>
    var transferencia = <?php echo json_encode($transferencia)?>;
    $('select[name=transferencia_estatus]').val(transferencia.transferencia_estatus);
    $('select[name=transferencia_estatus]').on('change',function(){
    $('textarea[name=transferencia_nota]').prop('required',false);
    $('#transferencia_nota_container').hide();
        var option = $('select[name=transferencia_estatus] option:selected').val();
        if(option == 'rechazada' || option == 'cancelada'){
            $('#transferencia_nota_container').show();
            $('textarea[name=transferencia_nota]').prop('required',true);
        }
    });
</script>