<div id="transferencias_control_container">
    <h1>Transferencias</h1>
    <?php if(count($successMessages)) :?>
    <div class="units-row">
        <?php foreach ($successMessages as $message) :?>
            <div class="unit-100">    
                <div class="tools-alert tools-alert-green">
                    <?php echo $message?>
                </div> 
            </div>
        <?php endforeach;?>
    </div>
<?php endif;?>
    <table>
        <thead>
            <tr>
                <th>Fecha</th>
                <th>Fecha Movimiento</th>
                <th>Remitente</th>
                <th>Receptor</th>
                <th>Estatus<th>
                <th>Comprobante<th>
                <th>Recibio<th>
                <th>Opciones<th>
            </tr>
        </thead>
        <tbody>
            <?php $entity = new Transferencia()?>
            <?php foreach($collection as $entity) : ?>
            <tr id="<?php echo $entity->getIdtransferencia()?>">
                <td><?php echo $entity->getTransferenciaCreadaen('d/m/Y')?></td>
                <td><?php echo $entity->getTransferenciaFechamovimiento('d/m/Y')?></td>
                <td><?php echo $entity->getClinicaRelatedByIdclinicaremitente()->getClinicaNombre()?></td>
                <td><?php echo $entity->getClinicaRelatedByIdclinicadestinataria()->getClinicaNombre()?></td>
                <td><?php echo $entity->getTransferenciaEstatus()?></td>
                <td><?php echo $entity->getTransferenciaComprobante()?></td>
                <td><?php echo $entity->getEmpleadoRelatedByIdempleadoreceptor()?></td>
                <td></td>
                <td></td>
                <td></td>
                <td class="tr_options"><a href="javascript:void(0)">Ver</a><a href="javascript:void(0)"> Cambiar status</a></td>
                </tr>
            <?php endforeach;?>
        </tbody>
    </table>
</div>
<script src="/js/inventario/existencias.js"></script>
<script>
    $('#definir_existencias_container').existencias();
    
    $('.add-existencia').on('loading.tools.modal', function(modal)
    {
        var $modalHeader = this.$modalHeader;
        $modalHeader.addClass('modal_header_action');
        
        var id = this.$element.closest('tr').attr('id');
        var type = this.$element.closest('tr').attr('data-type');
        
        var $modal = this ;
        
        this.createCancelButton('Cancelar');

        var buttonAction = this.createActionButton('Guardar');
        buttonAction.attr('data-action','submit');
        
        buttonAction.on('click', $.proxy(function()
        {
            
            var empty = false;
            $('input[name=cantidad]').removeClass('input-error');
            
            //Verificamos que no este vacio
            if($('input[name=cantidad]').val() == ""){
                empty=true;
                $('input[name=cantidad]').addClass('input-error');
            }
            
            if(!empty){
                
                var cantidad = $('input[name=cantidad]').val();
                
                //Hacemos la peticion ajax
                $.ajax({
                    url:'/inventario/existencias/nuevo',
                    dataType: 'json',
                    method:'POST',
                    data:{id:id,type:type,cantidad:cantidad},
                    success: function(data){
                        if(data.response){
                            $modal.close();
                            window.location.replace('/inventario/existencias');
                        }
                    }
                });
            }
            
            

            
        }, this));

    });
</script>