<?php 
    $this->headTitle()->prepend('Expedientes');
    echo $this->headTitle();
?>
<div id="expedientese_container">
    <h1>Expedientes</h1>
    <?php if(count($successMessages)) :?>
        <div class="units-row">
            <?php foreach ($successMessages as $message) :?>
                <div class="unit-100">    
                    <div class="tools-alert tools-alert-green">
                        <?php echo $message?>
                    </div> 
                </div>
            <?php endforeach;?>
        </div>
    <?php endif;?>
    <div class="units-row">
        <div class="unit-30">
            Clínica
            <select multiple="multiple" name="idclinica" class="width-100">
                <?php foreach ($clinicas as $clinica) : ?>
                    <option value="<?php echo $clinica->getIdclinica()?>"><?php echo $clinica->getClinicaNombre() ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <table class="table-clientes">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>Clínica</th>
                <th>Atendido por</th>
                <th>Fecha registro</th>
                <th>Celular</th>
                <th>Opciones</th>
            </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
</div>
<script src="/plugins/fullcalendar/moment.js"></script>
<script src="/js/pacientes/expediente.js"></script>
<script>
    $('#expedientese_container').expediente({
        session: <?php echo json_encode($session)?>,
    });   
</script>