<h1>Clínicas<a style="float: right; text-decoration: none"href="/catalogos/clinica/nuevo">Nuevo</a></h1>
<?php if(count($successMessages)) :?>
    <div class="units-row">
        <?php foreach ($successMessages as $message) :?>
            <div class="unit-100">    
                <div class="tools-alert tools-alert-green">
                    <?php echo $message?>
                </div> 
            </div>
        <?php endforeach;?>
    </div>
<?php endif;?>
<table>
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Dirección</th>
            <th>Registro patronal</th>
            <th>Telefono</th>
            <th>Opciones</th>
            
        </tr>
    </thead>
    <tbody>
        <?php foreach($collection as $entity) : ?>
            <tr>
                <td><?php echo $entity['clinica_nombre']?></td>
                <td><?php echo $entity['clinica_direccion']?></td>
                <td><?php echo $entity['clinica_registropatronal']?></td>
                <td><?php echo $entity['clinica_telefono']?></td>
                <td class="tr_options"><a>Editar</a><a>Eliminar</a></td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>