<?php 
    $this->headTitle()->prepend('Editar empleado');
    echo $this->headTitle();
?>
<div id="empleado_container">
    <h1>Empleado: <?php echo $form->get('empleado_nombre')->getValue()?></h1>
    <?php 
        $form->setAttribute('action', '/catalogos/empleado/editar/'.$id);
        $form->setAttribute('novalidate', true);
        $form->setAttribute('class', 'forms');
        $form->prepare();
        echo $this->form()->openTag($form); 
    ?>
    <div class="units-row">
        <div class="unit-100">
            <label>
                Nombre <span class="req">*</span>
                <?php echo $this->formText($form->get('empleado_nombre')); ?>
            </label>
        </div>
    </div>
    <div class="units-row">
        <div class="unit-50">
            <label>
                Número del seguro social
                <?php echo $this->formText($form->get('empleado_nss')); ?>
            </label>
        </div>
        <div class="unit-50">
            <label>
                RFC
                <?php echo $this->formText($form->get('empleado_rfc')); ?>
            </label>
        </div>
    </div>
    <div class="units-row">
        <div class="unit-50">
            <label>
                Calle
                <?php echo $this->formText($form->get('empleado_calle')); ?>
            </label>
        </div>
        <div class="unit-50">
            <label>
                Número
                <?php echo $this->formText($form->get('empleado_numero')); ?>
            </label>
        </div>
    </div>
    <div class="units-row">
        <div class="unit-50">
            <label>
                Colonia
                <?php echo $this->formText($form->get('empleado_colonia')); ?>
            </label>
        </div>
        <div class="unit-50">
            <label>
                Codigo postal
                <?php echo $this->formText($form->get('empleado_codigopostal')); ?>
            </label>
        </div>
    </div>
    <div class="units-row">
        <div class="unit-50">
            <label>
                Ciudad
                <?php echo $this->formText($form->get('empleado_ciudad')); ?>
            </label>
        </div>
        <div class="unit-50">
            <label>
                Sexo
                <?php echo $this->formSelect($form->get('empleado_sexo')); ?>
            </label>
        </div>
    </div>
    <div class="units-row">
        <div class="unit-50">
             <label style="margin-bottom: 0px">
                Fecha de nacimiento
            </label>
            <?php echo $this->formText($form->get('empleado_fechanacimiento')); ?>
            
        </div>
        <div class="unit-50">
            <label>
                Teléfono
                <?php echo $this->formText($form->get('empleado_telefono')); ?>
            </label>
        </div>
    </div>
    <div class="units-row">
        <div class="unit-50">
            <label>
                Celular
                <?php echo $this->formText($form->get('empleado_celular')); ?>
            </label>
        </div>
        <div class="unit-50">
            <label>
                Sueldo
                <?php echo $this->formText($form->get('empleado_sueldo')); ?>
            </label>
        </div>
    </div>
    <div class="units-row">
        
    </div>
    <div class="units-row">
        <div class="unit-100">
            <fieldset>
                <legend>Comprobantes</legend>
                <div class="units-row">
                    <div class="unit-50">
                        <label>Comprobante de domicilio</b</label>
                         
                        <?php echo $this->formFile($form->get('empleado_comprobantedomiclio')); ?>
                    </div>
                    <div class="unit-50">
                        <label>Comprobante de identificación</b</label>
                        <?php echo $this->formFile($form->get('empleado_comprobanteidentificacion')); ?>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
    <div class="units-row">
        <div class="unit-100">
            <fieldset>
                <legend>Comisiones</legend>
                <div class="units-row">
                    <div class="unit-20">
                        <label><b>Pago por comisión</b></label>
                        <ul class="forms-inline-list">
                            <li>
                                <input  type="radio" name="empleado_pagoporcomision" value="1">
                                <label for="radio-1">Si</label>
                            </li>
                            <li>
                                <input checked type="radio" name="empleado_pagoporcomision" value="0">
                                <label>No</label>
                            </li>
                        </ul>
                    </div>
                    <div class="unit-10">
                        <label style="height: 26px;"></label>
                        <label><b>Producto</b></label>
                        <label><b>Servicio</b></label>
                    </div>
                    <div class="unit-35">
                        <label><b>Tipo de comisión</b></label>
                        <select class="width-100" name="empleado_tipocomisionproducto" disabled="disabled" style="padding-right: 4px;">
                            <option value="cantidad">Cantidad fija</option>
                            <option value="porcentaje">Porcentaje</option>
                        </select>
                        <select class="width-100" style="padding-right: 4px; margin-top: 10px;" disabled="disabled" name="empleado_tipocomisionservicio">
                            <option value="cantidad">Cantidad fija</option>
                            <option value="porcentaje">Porcentaje</option>
                        </select>
                    </div>
                    <div class="unit-35">
                        <label><b>Cantidad de comisión</b></label>
                        <input class="width-100" type="text" value="" disabled="disabled" name="empleado_cantidadcomisionproducto">
                        <input class="width-100" type="text" name="empleado_cantidadcomisionservicio" disabled="disabled" value="" style="margin-top: 10px;">
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
    <div class="units-row">
        <div class="unit-100">
            <fieldset>
                <legend>Datos de acceso al sistema</legend>
                <div class="units-row" id="acceso_row">
                    <div class="unit-20">
                        <label>Rol</b</label>
                        <select class="width-100" name="accesos[0][idrol]">
                            <?php foreach($roles as $rol) :?>
                                <option value="<?php echo $rol['idrol']?>"><?php echo $rol['rol_nombre']?></option>
                            <?php endforeach;?>
                        </select>
                    </div>
                    <div class="unit-20">
                        <label>Nombre de usuario</b</label> <span class="req">*</span>
                        <input class="width-100" type="text"  name="accesos[0][username]" required value="<?php echo $empleado_accesos[0]['empleadoacceso_username']?>">
                    </div>
                    <div class="unit-20">
                        <label>Contraseña</b</label> <span class="req">*</span>
                        <input class="width-100" type="password"  name="accesos[0][password]" required value="<?php echo $empleado_accesos[0]['empleadoacceso_password']?>">
                    </div>
                    <div class="unit-20">
                        <label>Confirmar contraseña</b</label> <span class="req">*</span>
                        <input class="width-100 confirm" type="password" for="accesos[0][password]"  name="accesos[0][password_confirmar]" required value="<?php echo $empleado_accesos[0]['empleadoacceso_password']?>">
                    </div>
                    <div class="unit-10">
                        <a class="btn btn-blue" data-action="addAcceso" style="margin-top: 24px;">Agregar</a>
                    </div>
                </div>
                <?php if(isset($empleado_accesos[1])) :?>
                <div class="units-row">
                    <div class="unit-20">
                        <label>Rol</b</label>
                        <select class="width-100" name="accesos[1][idrol]">
                            <?php foreach($roles as $rol) :?>
                                <option value="<?php echo $rol['idrol']?>"><?php echo $rol['rol_nombre']?></option>
                            <?php endforeach;?>
                        </select>
                    </div>
                    <div class="unit-20">
                        <label>Nombre de usuario</b</label> 
                        <input class="width-100" type="text"  name="accesos[1][username]" required value="<?php echo $empleado_accesos[1]['empleadoacceso_username']?>">
                    </div>
                    <div class="unit-20">
                        <label>Contraseña</b</label> <span class="req">*</span>
                        <input class="width-100" type="password"  name="accesos[1][password]" required value="<?php echo $empleado_accesos[1]['empleadoacceso_password']?>">
                    </div>
                    <div class="unit-20">
                        <label>Confirmar contraseña</b</label> <span class="req">*</span>
                        <input class="width-100 confirm" for="accesos[1][password]" type="password"  name="accesos[1][password_confirmar]" required value="<?php echo $empleado_accesos[1]['empleadoacceso_password']?>">
                    </div>
                    <div class="unit-10" style="margin-top: 28px;">
                        <a id="removeRowAccess" style="text-decoration:none" href="javascript:void(0)">Eliminar</a>
                    </div>
                </div>
                <?php endif;?>
            </fieldset>
        </div>
    </div>
    <div class="units-row">
        <div class="unit-100">
            <fieldset>
                <legend>Fotografia</legend>
                <div class="units-row">
                    <div class="unit-centered unit-20">
                        <img style="width: 250px; height: 210px; cursor: pointer; padding-left: 35px; margin-bottom: 6px;" align="middle" id="empleado_foto" src="/img/empleados/default.jpg">
                        <input type="file" name="empleado_foto" style="display: none" accept="image/*">
                        <p id="eliminar_imagen" style="text-align: center; display: none"><a style="text-decoration: none" href="javascript:void(0)">Eliminar Imagen</a></p>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
    <div class="units-row">
        <div class="unit-centered unit-40"><button data-action="submit" class="btn btn-green">Guardar</button></div>
    </div>
</div>
<script src="/js/catalogos/empleado.js"></script>
<script>
    var empleado = <?php echo json_encode($entity)?>;
    var empleado_accesos = <?php echo json_encode($empleado_accesos)?>;
    
    
    //La seccion de comision
    if(empleado.empleado_tipocomisionproducto !=null){
        $('input[type=radio][name=empleado_pagoporcomision][value=1]').prop('checked',true);
        //Habilitamos selects
        $('select[name=empleado_tipocomisionproducto]').prop('disabled',false);
        $('select[name=empleado_tipocomisionproducto]').val(empleado.empleado_tipocomisionproducto);
        
        $('select[name=empleado_tipocomisionservicio]').prop('disabled',false);
        $('select[name=empleado_tipocomisionservicio]').val(empleado.empleado_tipocomisionservicio);
        
        //Los inputs
        $('input[name=empleado_cantidadcomisionproducto]').prop('disabled',false);
        $('input[name=empleado_cantidadcomisionproducto]').val(empleado.empleado_cantidadcomisionproducto);
        
        $('input[name=empleado_cantidadcomisionservicio]').prop('disabled',false);
        $('input[name=empleado_cantidadcomisionservicio]').val(empleado.empleado_cantidadcomisionservicio);
    }
    
     //La area de accessos
    var access_row_flag = false; 
    $('#acceso_row select').val(empleado_accesos[0].idrol);
    if(empleado_accesos.length > 1){
        $('#acceso_row a').addClass('btn-disabled');
        $('#acceso_row').next('div').find('select').val(empleado_accesos[1].idrol);
        access_row_flag = true;
        
    }

    $('#empleado_container').empleado({empleado:empleado,access_row_flag:access_row_flag });
    
   
</script>