<?php 
    $this->headTitle()->prepend('Empleados');
    echo $this->headTitle();
?>
<h1>Empleados<a style="float: right; text-decoration: none"href="/catalogos/empleado/nuevo">Nuevo</a></h1>
<?php if(count($successMessages)) :?>
    <div class="units-row">
        <?php foreach ($successMessages as $message) :?>
            <div class="unit-100">    
                <div class="tools-alert tools-alert-green">
                    <?php echo $message?>
                </div> 
            </div>
        <?php endforeach;?>
    </div>
<?php endif;?>
<table>
    <thead>
        <tr>
            <th>Fecha de registro</th>
            <th>Nombre</th>
            <th>Celular</th>
            <th>Número del seguro social</th>
            <th>Sueldo</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($collection as $entity) : ?>
            <?php $fecha_registro = new DateTime($entity['empleado_registradoen'])?>
            <tr id="<?php echo $entity['idempleado']?>">
                <td><?php echo $fecha_registro->format('d/m/Y')?></td>
                <td><?php echo $entity['empleado_nombre']?></td>
                <td><?php echo $entity['empleado_celular']?></td>
                <td><?php echo $entity['empleado_nss']?></td>
                <td><?php echo $entity['empleado_sueldo']?></td>
                <td class="tr_options"><a href="<?php echo '/catalogos/empleado/editar/'.$entity['idempleado']?>">Editar</a><a href="<?php echo '/catalogos/empleado/desbloquear/'.$entity['idempleado']?>">Desbloquear</a></td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>
<script>
$(function()
{
    
    $.ajax({
        url: '/json/lang_es_datatable.json',
        dataType: 'json',
        success: function(data){
            var table = $('table').DataTable({
                language:data,
            });
            table.on( 'draw', function () {
                $('[data-tools="modal"]').modal();
            });
        }
    });
    
    $('.delete-modal').on('loading.tools.modal', function(modal)
    {
        var $modalHeader = this.$modalHeader;
        $modalHeader.addClass('modal_header_warning');
        var id = this.$element.closest('tr').attr('id');
        var $modal = this ;
        
        this.createCancelButton('Cancelar');

        var buttonDelete = this.createDeleteButton('Eliminar');

        buttonDelete.on('click', $.proxy(function()
        {
            //Hacemos la peticion ajax
            $.ajax({
                url:'/catalogos/empleado/eliminar/'+id,
                dataType: 'json',
                method:'POST',
                success: function(data){
                    if(data.response){
                        $modal.close();
                        window.location.replace('/catalogos/empleado');
                    }
                }
            });

            
        }, this));

    });
    
    //Damos formato a nuestra taba
    $('table tr').each(function(){
       var str =  $(this).find('td').eq(4).text();
       $(this).find('td').eq(4).text(accounting.formatMoney(str));
      
    });
    
});
</script>