<?php 
    $this->headTitle()->prepend('Nuevo insumo');
    echo $this->headTitle();
?>
<div id="clinica_container">
    <h1>Nuevo insumo</h1>
    <?php 
        $form->setAttribute('action', '/catalogos/insumo/nuevo');
        $form->setAttribute('novalidate', true);
        $form->setAttribute('class', 'forms');
        $form->prepare();
        echo $this->form()->openTag($form); 
    ?>
    <div class="units-row">
        <div class="unit-50">
            <label>
                Nombre <span class="req">*</span>
                <?php echo $this->formText($form->get('insumo_nombre')); ?>
            </label>
        </div>
        <div class="unit-50">
            <label>
                Costo <span class="req">*</span>
                <?php echo $this->formText($form->get('insumo_costo')); ?>
            </label>
        </div>
    </div>
    <div class="units-row">
        <div class="unit-100">
            <label>
                Descripción
                <?php echo $this->formTextarea($form->get('insumo_descripcion')); ?>
            </label>
        </div>
    </div>
    <div class="units-row">
        <div class="unit-centered unit-40"><button data-action="submit" class="btn btn-green">Guardar</button></div>
    </div>
</div>
<script>
    $('input[name=insumo_costo]').numeric();
</script>
