<?php 
    $this->headTitle()->prepend('Reporte de empleados');
    echo $this->headTitle();
?>
<div id="reportes_container">
    <h1>Reportes de empleados<a style="float: right; text-decoration: none"href="/empleados/reportes/nuevo">Nuevo</a></h1>
    <?php if(count($successMessages)) :?>
        <div class="units-row">
            <?php foreach ($successMessages as $message) :?>
                <div class="unit-100">    
                    <div class="tools-alert tools-alert-green">
                        <?php echo $message?>
                    </div> 
                </div>
            <?php endforeach;?>
        </div>
    <?php endif;?>
    <div class="units-row">
        <div class="unit-30">
            Clínica
            <select multiple="multiple" name="idclinica" class="width-100">
                <?php foreach ($clinicas as $clinica) : ?>
                    <option value="<?php echo $clinica->getIdclinica()?>"><?php echo $clinica->getClinicaNombre() ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>
    <table>
        <thead>
            <tr>
                <th>Clínica actual</th>
                <th>Clínica suceso</th>
                <th>Fecha suceso</th>
                <th>Empleado</th>
                <th>Generado por</th>
                <th>Reporte</th>
                <th>Comentario</th>
                <th>Opciones</th>
            </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
</div>
<script src="/js/empleados/reportes.js"></script>
<script>
    var reportes = $('#reportes_container').reporteEmpleados({
        idclinica: <?php echo $idclinica?>,
    });
    reportes.init();
    
</script>