<?php 
    $form->setAttribute('action', '/login/in');
    $form->setAttribute('novalidate', true);
    $form->setAttribute('class', 'forms');
    $form->prepare();
?>
<div class="units-row">
    <div class="unit-centered unit-40">
        <div id="login_container" class="text-centered">
            <?php if(count($errorMessages)) :?>
                <?php foreach ($errorMessages as $message) :?>
                    <div class="tools-alert tools-alert-red">
                        <?php echo $message?>
                    </div> 
                <?php endforeach;?>
            <?php endif;?>
            <img  src="/img/logo/top_logo.png">
            <?php echo $this->form()->openTag($form); ?>
            <input name="redirect" value="<?php $redirect?>" type="hidden">
            <div class="units-row">
                <div class="unit-100">
                    <label>
                        Nombre de usuario <span class="req">*</span>
                        <?php echo $this->formText($form->get('empleadoacceso_username')); ?>
                    </label>
                </div>
                <div class="unit-100">
                    <label>
                        Contraseña <span class="req">*</span>
                        <?php echo $this->formPassword($form->get('empleadoacceso_password')); ?>
                    </label>
                </div>
                <div class="units-row" style="margin-top: 20px;">
                    <div class="unit-100"><button data-action="submit" class="btn btn-green width-100">Entrar</button></div>
                </div>
            </div>
             <?php echo $this->form()->closeTag() ?>
        </div>
    </div>
</div>