<?php 
    $this->headTitle()->prepend('Compras');
    echo $this->headTitle();
?>
<h1>Compras<a style="float: right; text-decoration: none"href="/compras/nuevo">Nuevo</a></h1>
<?php if(count($successMessages)) :?>
    <div class="units-row">
        <?php foreach ($successMessages as $message) :?>
            <div class="unit-100">    
                <div class="tools-alert tools-alert-green">
                    <?php echo $message?>
                </div> 
            </div>
        <?php endforeach;?>
    </div>
<?php endif;?>
<fieldset>
    <legend>Filtros</legend>
    <div class="units-row">
        <div class="unit-100" id="filter_container">
            <label style="display: block">Filtrar por periodo de tiempo</label>
            <input placeholder="Desde" type="email" name="compras_from" class="width-6" />
            <input placeholder="Hasta" type="email" name="compras_to" class="width-6" />
            <button id="filterbydate" class="btn btn-blue" style="height: 30px;"><i class="fa fa-filter"></i> </button>
        </div>
    </div>
</fieldset>
<table class="table-compras">
    <thead>
        <tr>
            <th>Fecha</th>
            <th>Folio</th>
            <th>Proveedor</th>
            <th>Importe</th>
            <th>Estatus</th>
            <th>Comprobante</th>
            <th>Opciones</th>   
        </tr>
    </thead>
    <tbody>
        <?php foreach($collection as $entity) : ?>
            <tr id="<?php echo $entity->getIdCompra()?>">
                <td><?php echo $entity->getCompraFecha('d/m/Y')?></td>
                <td><?php echo $entity->getCompraFolio()?></td>
                <td><?php echo $entity->getProveedor()->getProveedorNombre()?></td>
                <td class="importe"><?php echo $entity->getCompraImporte()?></td>
                <td><?php echo $entity->getCompraStatus()?></td>
                <td><?php echo $entity->getCompraComprobante()?></td>
                <td class="tr_options"><a href="<?php echo '/compras/editar/'.$entity->getIdCompra()?>">Editar</a><a class="delete-modal" href="javascript:void(0)" data-tools="modal" data-width="700" data-title="<h2>Advertencia</h2>" data-content="/compras/eliminar?html=true" >Eliminar</a></td>
            </tr>
        <?php endforeach;?>
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">Total</td>
            <td id="total">0</td>
            <td colspan="3"></td>
        </tr>
    </tfoot>
</table>
<script>
$(function()
{   
    var table;
    var calcularTotal = function(){
        var total = 0;
        $('.table-compras tbody td.importe').filter(function(){
            total+= accounting.unformat($(this).text());
        });
        $('.table-compras tfoot #total').text(accounting.formatMoney(total));
       
    }
    
    calcularTotal();
    //Inicializamos nuestros calendarios del filtro de fechas
    var pickdateFrom = $('input[name=compras_from]').pickadate({
        monthsFull: [ 'enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre' ],
        monthsShort: [ 'ene', 'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'nov', 'dic' ],
        weekdaysFull: [ 'domingo', 'lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado' ],
        weekdaysShort: [ 'dom', 'lun', 'mar', 'mié', 'jue', 'vie', 'sáb' ],
        today: 'hoy',
        clear: 'borrar',
        close: 'cerrar',
        firstDay: 1,
        format: 'd !de mmmm !de yyyy',
        formatSubmit: 'yyyy/mm/dd',
        selectYears: true,
        selectMonths: true,
        selectYears: 25,
    });
            
    //Inicializamos nuestros calendarios del filtro de fechas
    var pickdateTo= $('input[name=compras_to]').pickadate({
        monthsFull: [ 'enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre' ],
        monthsShort: [ 'ene', 'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'nov', 'dic' ],
        weekdaysFull: [ 'domingo', 'lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado' ],
        weekdaysShort: [ 'dom', 'lun', 'mar', 'mié', 'jue', 'vie', 'sáb' ],
        today: 'hoy',
        clear: 'borrar',
        close: 'cerrar',
        firstDay: 1,
        format: 'd !de mmmm !de yyyy',
        formatSubmit: 'yyyy/mm/dd',
        selectYears: true,
        selectMonths: true,
        selectYears: 25,
    });
    
    $('button#filterbydate').on('click',function(){
                
        var empty = false;

         $('#filter_container input:visible').removeClass('input-error');

        $('#filter_container input:visible').each(function(){
            if($(this).val() == ""){
                empty = true;
                $(this).addClass('input-error');
            }
        });

        if(!empty){
           var from = $('input[name=compras_from_submit]').val();
           var to = $('input[name=compras_to_submit]').val();

           $.ajax({
                url:'/compras/filterbydate',
                dataType: 'json',
                method:'POST',
                data:{from:from,to:to},
                success:function(data){
                    table.clear();
                    table.destroy();
                    $('table.table-compras tbody tr').remove();
                    $.each(data,function(){
                        var compra_comprobante = this.compra_comprobante;
                        if(compra_comprobante==null){
                            compra_comprobante="";
                        }
                        var tr = $('<tr>');
                        tr.append('<td>'+this.compra_fecha+'</td>') ;
                        tr.append('<td>'+this.compra_folio+'</td>') ;
                        tr.append('<td>'+this.proveedor_nombre+'</td>') ;
                        tr.append('<td class="importe">'+accounting.formatMoney(this.compra_importe)+'</td>') ;
                        tr.append('<td>'+this.compra_status+'</td>') ;
                        tr.append('<td>'+compra_comprobante+'</td>') ;
                        tr.append('<td class="tr_options"><a href="/compras/editar/'+this.idcompra+'">Editar</a><a class="delete-modal" href="javascript:void(0)" data-tools="modal" data-width="700" data-title="<h2>Advertencia</h2>" data-content="/compras/eliminar?html=true" >Eliminar</a></td>');
                        
                        $('table.table-compras tbody').append(tr);

                        
                    });
                    
                    //Damos formato a nuestra taba
                    $('.table-compras tr').each(function(){
                       var str =  $(this).find('td').eq(3).text();
                       $(this).find('td').eq(3).text(accounting.formatMoney(str));
                       
                       var str =  $(this).find('td').eq(5).text();
                       console.log(typeof str);
                       if(str != ""){
                         $(this).find('td').eq(5).html('<a href="'+str+'"><img style="width:20px;height:20px;" src="/img/icons/pdf_icon.png"></a>');
                       }else{
                        $(this).find('td').eq(5).text('N/D');
                       }

                    });
                    
                    $('.delete-modal').on('loading.tools.modal', function(modal)
                        {
                            var $modalHeader = this.$modalHeader;
                            $modalHeader.addClass('modal_header_warning');
                            var id = this.$element.closest('tr').attr('id');
                            var $modal = this ;

                            this.createCancelButton('Cancelar');

                            var buttonDelete = this.createDeleteButton('Eliminar');

                            buttonDelete.on('click', $.proxy(function()
                            {
                                //Hacemos la peticion ajax
                                $.ajax({
                                    url:'/compras/eliminar/'+id,
                                    dataType: 'json',
                                    method:'POST',
                                    success: function(data){
                                        if(data.response){
                                            $modal.close();
                                            window.location.replace('/compras');
                                        }
                                    }
                                });


                            }, this));

                        });
                    
                    calcularTotal();
                         
                    $.ajax({
                        url: '/json/lang_es_datatable.json',
                        dataType: 'json',
                        success: function(data){
                            table = $('.table-compras').DataTable({
                                language:data,
                            });
                            table.on( 'draw', function () {
                                $('[data-tools="modal"]').modal();
                            });
                        }
                    });
                }
           });

        }


    });
    
    
    $.ajax({
        url: '/json/lang_es_datatable.json',
        dataType: 'json',
        success: function(data){
            table = $('.table-compras').DataTable({
                language:data,
            });
            table.on( 'draw', function () {
                $('[data-tools="modal"]').modal();
            });
        }
    });
    
    
    $('.delete-modal').on('loading.tools.modal', function(modal)
    {
        var $modalHeader = this.$modalHeader;
        $modalHeader.addClass('modal_header_warning');
        var id = this.$element.closest('tr').attr('id');
        var $modal = this ;
        
        this.createCancelButton('Cancelar');

        var buttonDelete = this.createDeleteButton('Eliminar');

        buttonDelete.on('click', $.proxy(function()
        {
            //Hacemos la peticion ajax
            $.ajax({
                url:'/compras/eliminar/'+id,
                dataType: 'json',
                method:'POST',
                success: function(data){
                    if(data.response){
                        $modal.close();
                        window.location.replace('/compras');
                    }
                }
            });

            
        }, this));

    });
    
     //Damos formato a nuestra taba
    $('.table-compras tr').each(function(){
       var str =  $(this).find('td').eq(3).text();
       $(this).find('td').eq(3).text(accounting.formatMoney(str));
       
       var str =  $(this).find('td').eq(5).text();
       if(str != ""){
         $(this).find('td').eq(5).html('<a href="'+str+'"><img style="width:20px;height:20px;" src="/img/icons/pdf_icon.png"></a>');
       }else{
        $(this).find('td').eq(5).text('N/D');
       }
      
    });
});
</script>