<h1>Compras<a style="float: right; text-decoration: none"href="/compras/nuevo">Nuevo</a></h1>
<?php if(count($successMessages)) :?>
    <div class="units-row">
        <?php foreach ($successMessages as $message) :?>
            <div class="unit-100">    
                <div class="tools-alert tools-alert-green">
                    <?php echo $message?>
                </div> 
            </div>
        <?php endforeach;?>
    </div>
<?php endif;?>
<table>
    <thead>
        <tr>
            <th>Fecha</th>
            <th>Folio</th>
            <th>Proveedor</th>
            <th>Importe</th>
            <th>Estatus</th>
            <th>Comprobante</th>
            <th>Opciones</th>   
        </tr>
    </thead>
    <tbody>
        <?php foreach($collection as $entity) : ?>
            <tr id="<?php echo $entity->getIdCompra()?>">
                <td><?php echo $entity->getCompraFecha('d/m/Y')?></td>
                <td><?php echo $entity->getCompraFolio()?></td>
                <td><?php echo $entity->getProveedor()->getProveedorNombre()?></td>
                <td><?php echo $entity->getCompraImporte()?></td>
                <td><?php echo $entity->getCompraStatus()?></td>
                 <td><?php echo $entity->getCompraComprobante()?></td>
                <td class="tr_options"><a href="<?php echo '/compras/editar/'.$entity->getIdCompra()?>">Editar</a><a class="delete-modal" href="javascript:void(0)" data-tools="modal" data-width="700" data-title="<h2>Advertencia</h2>" data-content="/compras/eliminar?html=true" >Eliminar</a></td>
            </tr>
        <?php endforeach;?>
    </tbody>
</table>
<script>
$(function()
{
    $('.delete-modal').on('loading.tools.modal', function(modal)
    {
        var $modalHeader = this.$modalHeader;
        $modalHeader.addClass('modal_header_warning');
        var id = this.$element.closest('tr').attr('id');
        var $modal = this ;
        
        this.createCancelButton('Cancelar');

        var buttonDelete = this.createDeleteButton('Eliminar');

        buttonDelete.on('click', $.proxy(function()
        {
            //Hacemos la peticion ajax
            $.ajax({
                url:'/compras/eliminar/'+id,
                dataType: 'json',
                method:'POST',
                success: function(data){
                    if(data.response){
                        $modal.close();
                        window.location.replace('/compras');
                    }
                }
            });

            
        }, this));

    });
    
     //Damos formato a nuestra taba
    $('table tr').each(function(){
       var str =  $(this).find('td').eq(3).text();
       $(this).find('td').eq(3).text(accounting.formatMoney(str));
       
       var str =  $(this).find('td').eq(5).text();
       if(str != ""){
         $(this).find('td').eq(5).html('<a href="'+str+'"><img style="width:20px;height:20px;" src="/img/icons/pdf_icon.png"></a>');
       }else{
        $(this).find('td').eq(5).text('N/D');
       }
      
    });
});
</script>