<?php 
    $this->headTitle()->prepend('Nueva compra');
    echo $this->headTitle();
?>
<h1>Nueva compra</h1>
<div id="compra_container">
    <form class="forms" enctype="multipart/form-data" novalidate="1" action="/compras/nuevo" name="compraForm" method="post">
        <div class="units-row">
            <div class="unit-100">
                <fieldset>
                    <legend>Información general</legend>
                    <div class="units-row">
                        <div class="unit-50">
                            Proveedor
                            <select class="width-100" name="idproveedor" style="height: 29px;">
                                <?php foreach ($proveedores as $proveedor) :?>
                                    <option value="<?php echo $proveedor['idproveedor']?>"><?php echo $proveedor['proveedor_nombre']?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                    </div>
                    <div class="units-row">
                        <div class="unit-25">
                            <label style="margin-bottom: 0px">
                                Fecha de compra
                                <span class="req">*</span>
                            </label>
                            <input class="width-100" type="text" required="required" name="compra_fecha">
                        </div>
                        <div class="unit-25">
                            <label>
                                No. Folio
                                <span class="req">*</span>
                                <input class="width-100" type="text" required="required" name="compra_folio">
                            </label>
                        </div>
                        <div class="unit-25">
                            <label>
                                Fecha de pago <span class="req">*</span>
                                <input class="width-100" type="text" required="required" name="compra_pagaren">
                            </label>
                        </div>
                        <div class="unit-25">
                            Estatus
                            <select class="width-100" name="compra_status" style="height: 29px;">
                                <option value="pagada">Pagada</option>
                                <option value="no pagada">No pagada</option>
                            </select>
                        </div>
                    </div>
                </fieldset>
            </div>
        </div>
        <div class="units-row">
            <div class="unit-100">
                <fieldset>
                    <legend>Comprabante de compra</legend>
                        <label>
                        Comprobante de compra
                        <input class="width-100" type="file" accept="image/*" name="compra_comprobante">
                    </label> 
                </fieldset>
            </div>
        </div>
        <div class="units-row" id="details_container">
            <fieldset>
                <legend>Detalles de la compra</legend>
                <div class="unit-100">
                    <div class="units-row">
                        <div class="unit-50">
                            Productos/Insumos
                            <select  class="width-100" style="height: 29px;">
                                <optgroup label="Productos">
                                    <?php foreach ($productos as $producto) :?>
                                        <option data-type="producto" value="<?php echo $producto['idproducto']?>"><?php echo $producto['producto_nombre']?></option>
                                    <?php endforeach;?>
                                </optgroup>
                                <optgroup label="Insumos">
                                     <?php foreach ($insumos as $insumo) :?>
                                        <option data-type="insumo" value="<?php echo $insumo['idinsumo']?>"><?php echo $insumo['insumo_nombre']?></option>
                                    <?php endforeach;?>
                                </optgroup>
                            </select>
                        </div>  
                        <div class="unit-10">
                            <label>
                                Cantidad <span class="req">*</span>
                                <input class="width-100" type="text"  name="compradetalle_cantidad">
                            </label>
                        </div>
                        <div class="unit-20">
                            <label>
                                Costo unitario <span class="req">*</span>
                                <input class="width-100" type="text" name="compradetalle_costounitario">
                            </label>
                        </div>
                        <div class="unit-20" style="margin-left: 20px;">
                            <label>
                                 <a class="btn btn-blue" data-action="addProducto" style="margin-top: 22px; margin-right: 20px;">Agregar</a>
                            </label>
                        </div>
                    </div>
                </div>
            </fieldset>
        </div>
        <div class="units-row">
            <div class="unit-100">
                <table>
                    <thead>
                        <tr>
                            <th>Cantidad</th>
                            <th>Tipo</th>
                            <th>Descripción</th>
                            <th>Costo</th>
                            <th>Subtotal</th>
                            <th>Opciones</th>
                        </tr>
                    </thead>
                    <tbody>

                    </tbody>
                    <tfoot>
                        <tr>
                        <input name="compra_importe" type="hidden" value="0">
                            <td colspan="5">Total</td>
                            <td id="total">$ 0</td>
                        </tr>
                    </tfoot>
                </table>
            </div> 
        </div>
        <div class="units-row">
            <div class="unit-centered unit-40">
                <button class="btn btn-green" data-action="submit">Guardar</button>
            </div>
        </div>
    </form>
</div>
<script src="/js/compras/compra.js"></script>
<script>
    $('#compra_container').compra();
</script>